# .travis.yml - Travis CI service configuration for GEOS
#
#
# This is free software; you can redistribute and/or modify it under
# the terms of the GNU Lesser General Public Licence as published
# by the Free Software Foundation.
# See the COPYING file for more information.
#

sudo: false

language: cpp

compiler:
  - clang
  - g++

env:
  - GEOS_BUILD=autotools CFLAGS='-m64 -g -O2' CXXFLAGS='-m64 -g -O2'
  - GEOS_BUILD=autotools CFLAGS='-m32 -g -O2' CXXFLAGS='-m32 -g -O2'

matrix:
  fast_finish: true
  include:
    - compiler: g++
      cache: ccache
      env: GEOS_BUILD=autotools CFLAGS='-m64 --coverage' CXXFLAGS='-m64 -g -O0 --coverage' RUN_PROFILER=TRUE

# Install operating system addons.
# @affectOnBuild  Broken
#   If application return non-zero, the build is broken and stops.
addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - lcov


# Custom commands to run before installing your application.
#
# @affectOnBuild  Errored
#   If an application returns a non-zero, the build is errored and stops.
before_install:
  # Install coveralls.io upload module
  - gem update --system


  # Do the steps necessary to install your application.
  #
  # @affectOnBuild  Errored
  #   If an application returns a non-zero, the build is errored and stops.
install:
  - |
    if [ "${RUN_PROFILER}" == "TRUE" ]; then
      gem install coveralls-lcov
    fi


# Custom commands to run before running your application.
#
# @affectOnBuild  Errored
#   If an application returns a non-zero, the build is errored and stops.
before_script:
  - |
    if [ "${RUN_PROFILER}" == "TRUE" ]; then
      lcov --directory ${TRAVIS_BUILD_DIR} --zerocounters
    fi


# Returns a non-zero exit code, the build is failed, but continues to run
# before being marked as failed.
script:
  - ${TRAVIS_BUILD_DIR}/tools/ci/script.sh


# Does not affect build results.
after_script: true


# Does not affect build results.
after_success:
  - |
    if [ "${RUN_PROFILER}" == "TRUE" ]; then
      lcov --compat-libtool --directory ${TRAVIS_BUILD_DIR} --capture --output-file coverage.info
      coveralls-lcov coverage.info
    fi


  # Does not affect build results.
after_failure: true
