# .travis.yml - Travis CI service configuration for GEOS
#
#
# This is free software; you can redistribute and/or modify it under
# the terms of the GNU Lesser General Public Licence as published
# by the Free Software Foundation.
# See the COPYING file for more information.
#

dist: trusty
sudo: false
cache:
  - ccache

language: cpp

compiler:
  - clang
  - g++

env:
  - GEOS_BUILD_TOOL=autotools CFLAGS='-m64' CXXFLAGS='-m64'
  - GEOS_BUILD_TOOL=autotools CFLAGS='-m32' CXXFLAGS='-m32'

matrix:
  fast_finish: true
  include:
    - compiler: g++
      env: GEOS_BUILD_TOOL=autotools CFLAGS='-m64 -g -O0' CXXFLAGS='-m64 -g -O0 --coverage'

# Install operating system addons.
# @affectOnBuild  Broken
#   If application return non-zero, the build is broken and stops.
addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libc6
      - libc6-dev
      - libc6.1-dev-alpha-cross
      - build-essential
      - make
      - lcov


# Custom commands to run before installing your application.
#
# @affectOnBuild  Errored
#   If an application returns a non-zero, the build is errored and stops.
before_install:
  # Install coveralls.io upload module
  - gem update --system


  # Do the steps necessary to install your application.
  #
  # @affectOnBuild  Errored
  #   If an application returns a non-zero, the build is errored and stops.
install:
  - gem install coveralls-lcov


# Custom commands to run before running your application.
#
# @affectOnBuild  Errored
#   If an application returns a non-zero, the build is errored and stops.
before_script:
  - lcov --directory ${TRAVIS_BUILD_DIR} --zerocounters


# Returns a non-zero exit code, the build is failed, but continues to run
# before being marked as failed.
script:
  - ${TRAVIS_BUILD_DIR}/tools/ci/script.sh


# Does not affect build results.
after_script: true


# Does not affect build results.
after_success:
  - lcov --compat-libtool --directory ${TRAVIS_BUILD_DIR}/src --capture --output-file coverage.info
  - coveralls-lcov coverage.info


  # Does not affect build results.
after_failure: true
