# .travis.yml - Travis CI service configuration for GEOS
#
#
# This is free software; you can redistribute and/or modify it under
# the terms of the GNU Lesser General Public Licence as published
# by the Free Software Foundation.
# See the COPYING file for more information.
#
sudo: false

language: cpp

compiler:
    - clang
    - g++

env:
    - GEOS_BUILD_TOOL=autotools CFLAGS=-m64 CXXFLAGS=-m64
    - GEOS_BUILD_TOOL=autotools CFLAGS=-m32 CXXFLAGS=-m32

matrix:
  fast_finish: true

addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - make

before_install:
    - pip install --user cpp-coveralls

script: ./tools/ci/script.sh

after_success:
  - coveralls --exclude tests --exclude tools --exclude web --gcov-options '\-lp'
