# .travis.yml - Travis CI service configuration for GEOS
#
#
# This is free software; you can redistribute and/or modify it under
# the terms of the GNU Lesser General Public Licence as published
# by the Free Software Foundation.
# See the COPYING file for more information.
#

sudo: false

language: cpp

compiler:
    - clang
    - g++

env:
  - GEOS_BUILD_TOOL=autotools CFLAGS=-m64 CXXFLAGS=-m64
  - GEOS_BUILD_TOOL=autotools CFLAGS=-m32 CXXFLAGS=-m32

matrix:
  fast_finish: true

# Install operating system addons.
# @affectOnBuild  Broken
#   If application return non-zero, the build is broken and stops.
addons:
  apt:
    source:
      - ppa:ondrej/php # Enable PHP 5.5, 5.6, 7.0
    packages:
      - gcc-multilib
      - g++-multilib
      - make
      - lcov
      - php5.6
      - php-dev
      - php-composer


# Custom commands to run before installing your application.
#
# @affectOnBuild  Errored
#   If an application returns a non-zero, the build is errored and stops.
before_install:
  # Install PHPUnit with composer
  - composer self-update
  - composer global require phpunit/phpunit
  # Install coveralls.io upload module
  - gem update --system
  - gem install coveralls-lcov


  # Do the steps necessary to install your application.
  #
  # @affectOnBuild  Errored
  #   If an application returns a non-zero, the build is errored and stops.
install: true


# Custom commands to run before running your application.
#
# @affectOnBuild  Errored
#   If an application returns a non-zero, the build is errored and stops.
before_script:
  - lcov --directory ${TRAVIS_BUILD_DIR} --zerocounters


# Returns a non-zero exit code, the build is failed, but continues to run
# before being marked as failed.
script:
  - ${TRAVIS_BUILD_DIR}/tools/ci/script.sh


# Does not affect build results.
after_script: true


# Does not affect build results.
after_success:
  - lcov --compat-libtool --directory ${TRAVIS_BUILD_DIR} --capture --output-file coverage.info
  - coveralls-lcov ${TRAVIS_BUILD_DIR}/coverage.info


  # Does not affect build results.
after_failure: true
