# .travis.yml - Travis CI service configuration for GEOS
#
#
# This is free software; you can redistribute and/or modify it under
# the terms of the GNU Lesser General Public Licence as published
# by the Free Software Foundation.
# See the COPYING file for more information.
#
sudo: false

language:
  - cpp
  - php

compiler:
    - clang
    - g++

php:
  - 5.3
  - 5.6
  - 7.0
  - hhvm

env:
    - GEOS_BUILD_TOOL=autotools CFLAGS=-m64 CXXFLAGS=-m64
    - GEOS_BUILD_TOOL=autotools CFLAGS=-m32 CXXFLAGS=-m32

matrix:
  fast_finish: true

addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - make
    - lcov

before_install:
  - gem install coveralls-lcov

before_script: # (optional: for paranoiacs only)
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  - ${TRAVIS_BUILD_DIR}/tools/ci/script.sh

after_success:
  - lcov --compat-libtool --directory ${TRAVIS_BUILD_DIR} --capture --output-file coverage.info
  - coveralls-lcov ${TRAVIS_BUILD_DIR}/coverage.info
